version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "aws-test-ui-bucket"
        BUILD_FOLDER: "dist"
phases:
  pre_build:
    commands:
      - aws s3 rm s3://${S3_BUCKET} --recursive
  install:
    runtime-versions:
        nodejs: 14
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes